[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
namespaces = true
where = ["src/"]
include = [
    "zcli",
]

[project]
name = "zacharyacoon.zcli"
version = "1.0.0"
