[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
namespaces = true
where = ["packages/"]
include = [
    "zacharyacoon.zlogging",
]

[project]
name = "zacharyacoon"
dynamic = ["version"]
