[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
namespaces = true
where = ["src/"]
include = [
    "zlogging",
]

[project]
name = "zacharyacoon.zlogging"
version = "1.0.1"
